import './globals.css'
import { Inter, Lora, Roboto_Serif } from 'next/font/google'
import { ClerkProvider } from '@clerk/nextjs'

const inter = Inter({ subsets: ['latin'] })
const roboto = Roboto_Serif({ subsets: ['latin'] })
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${roboto.className} prose`}>{children}</body>
      </html>
    </ClerkProvider>
  )
}
